### ISSUE TITLE
Define database schema

### ISSUE THREAD

**Issue by Zobeir-Rigi** [BoshraM/ldn9-Ctrl-Shift-Learn#29]
Create the schema and pull it, so the team can create the same database with the same tables. 

take github username give cohort

region/cohort
-  id: 1
-  name: LDN9
-  start_date

trainee
- id: 1
- gitHub_user_name: Sam1000
- full_name: Sam Smith
- email: sam@example.com
- cohort_id: 1 

![Image](https://user-images.githubusercontent.com/2520859/248781750-6583c47b-3289-4731-97a1-1bc6600a443a.png)

**Comment by OlenaReukova** [comment]
done.
