### ISSUE TITLE
Designing trainee dashboeard with Figma

### ISSUE THREAD

**Issue by BoshraM** [BoshraM/ldn9-Ctrl-Shift-Learn#75]

**Comment by OlenaReukova** [comment]
<img width="387" alt="Previous Milestone" src="https://github.com/BoshraM/ldn9-Ctrl-Shift-Learn/assets/34659641/b2ff2f74-6619-4175-af53-67bfeac85d5b">
<img width="387" alt="Next Milestone" src="https://github.com/BoshraM/ldn9-Ctrl-Shift-Learn/assets/34659641/7682e45f-18ea-46b2-9de3-bd9d80666519">
